# Detection thresholds
PORTSCAN_THRESHOLD = 15
DNSQ_THRESHOLD = 15
DNS_LENGTH_THRESHOLD = 50
ICMP_FLOOD_THRESHOLD = 50
SYN_FLOOD_THRESHOLD = 100

# Claude API settings
MAX_TOKENS = 1024
MODEL = "claude-sonnet-4-5"

# Report settings
REPORT_DIR = "reports/"